name       : perl-xml-libxml-simple
version    : '0.99'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MARKOV/XML-LibXML-Simple-0.99.tar.gz : 14fe45c9fcb36c1cf14ac922da4439f1f83d451a5e70aa7177cb6edb705c9e44
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module is a blunt rewrite of XML::Simple (by Grant McLean) to use
    the XML::LibXML parser for XML structures
description: |
    This module is a blunt rewrite of XML::Simple (by Grant McLean) to use the XML::LibXML parser for XML structures
builddeps  :
    - perl-xml-libxml
rundeps    :
    - perl-scalar-list-utils
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
