name       : perl-xml-libxml-simple
version    : '1.01'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/M/MA/MARKOV/XML-LibXML-Simple-1.01.tar.gz : cd98c8104b70d7672bfa26b4513b78adf2b4b9220e586aa8beb1a508500365a6
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module is a blunt rewrite of XML::Simple (by Grant McLean) to use the XML::LibXML parser for XML structures
description: |
    This module is a blunt rewrite of XML::Simple (by Grant McLean) to use the XML::LibXML parser for XML structures
builddeps  :
    - perl-xml-libxml
rundeps    :
    - perl-scalar-list-utils
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
