name       : perl-xml-libxml-simple
version    : 0.97
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MA/MARKOV/XML-LibXML-Simple-0.97.tar.gz : 1ccc5fb166586232c939b27244abf1bb7627c7d2fbabe33a654cfcf6c7a416bd
license    : GPL-2.0
component  : programming.perl
summary    : This module is a blunt rewrite of XML::Simple (by Grant McLean) to use
    the XML::LibXML parser for XML structures
description: |
    This module is a blunt rewrite of XML::Simple (by Grant McLean) to use the XML::LibXML parser for XML structures
rundeps    :
    - perl-scalar-list-utils
    - perl-xml-libxml
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
